### ISSUE TITLE
Resume scan after code scanned

### ISSUE THREAD

**Issue by araimbekoff** [pulilab/vue-qr-reader#1]
Excellent component!
And now tell me how to resume scanning after the code has been scanned and the flag is set by default: stop-on-scanned = "true"

**Comment by lordfuoco** [comment]
@araimbekoff Thank you!
At the moment a 'manual resume' is not implemented, you can still achieve it by adding a v-if that remove the component and put it back.

If manually triggering the scan is a interesting feature for you we would welcome any PR, I will open a dedicated issue  (#2) about this. If you are not in a position to make a PR or unwillingly to do so we will consider doing it in the near future!
