### ISSUE TITLE
Camera Permissions

### ISSUE THREAD

**Issue by essamtariq123** [pulilab/vue-qr-reader#15]
the documentation does not show how the camera will ask permissions. when i follow step by step it doesn't even access the camera

**Comment by lordfuoco** [comment]
@essamtariq123 the permission is asked in the standard browser popup, note that if you are not on localhost you need to use https for it to work. Do you have any warning / error in your console ?

**Comment by essamtariq123** [comment]
@lordfuoco thanks for the quick reply. No I don't have any error what so ever in the console in-fact its blank

**Comment by lordfuoco** [comment]
@essamtariq123 if you open the documentation does the demo work well for you ?

**Comment by essamtariq123** [comment]
yes it does the camera works and everything works. but I am trying to get the permissions in my site for camera. the documentation does not guide that part or am I missing something?

**Comment by lordfuoco** [comment]
@essamtariq123 the permission dialog is triggered once per each domain and only by the browser, is not something you have control of ( for security reason ) if you want to see it again go in the address bar on the left ( if you use chrome ) and reset your choices about camera

**Comment by essamtariq123** [comment]
<vue-qr-reader v-on:code-scanned="codeArrived"/>

doesn't this give the camera permissions? or do i have to write the camera permission code myself? you are getting my point right? sorry if I am not able to convey the message

**Comment by essamtariq123** [comment]
I configured the plugin and a better way to understand is with this tutorial 
https://www.youtube.com/watch?v=Hc7GE3ENz7k&t=1s

thanks for the help @lordfuoco
