### ISSUE TITLE
Scanner not scanning anymore

### ISSUE THREAD

**Issue by a-rmz** [pulilab/vue-qr-reader#17]
## Steps to reproduce:
1. Enter to the website using the QR scanner (e.g. https://pulilab.github.io/vue-qr-reader/#/demo)
2. Try to scan any QR code
---
Even though you can see the video in the camera, the code is not being found. This started happening recently (not more than two weeks ago).

Tested in Firefox Developer Edition, Chrome and Safari.

**Comment by lordfuoco** [comment]
Ehi! Thank you I will l take a look!

**Comment by DonNicoJs** [comment]
@a-rmz For me it works, tried just now, is the issue still open for you ?
