### ISSUE TITLE
.container  class clashing with Bootstrap

### ISSUE THREAD

**Issue by fernandoagarcia** [pulilab/vue-qr-reader#19]
Hey Guys, 

Great scanner. One issue is that the .container class is clashing with bootstrap container since its not being nested under its wrapper component. Basically this overwrites the global bootstrap class. Is there anything we can do to remove it or rename it?

**Comment by DonNicoJs** [comment]
@fernandoagarcia Hi sure is just an internal class, PR welcomed to fix it :) just rename the class and the css

**Comment by nmezzopera** [comment]
Released :)
