### ISSUE TITLE
scanner onReady|onErorr 

### ISSUE THREAD

**Issue by araimbekoff** [pulilab/vue-qr-reader#3]
It is good to have $emit methods from component for displaying preloader to the User.
Thanx!

**Comment by lordfuoco** [comment]
@araimbekoff What we are thinking is to offer a slot option to allow a configurable preloader that the plugin would expose.

What do you think ?

**Comment by araimbekoff** [comment]
not bad. with the condition that the component is transferred to an arbitrary

**Comment by lordfuoco** [comment]
Closing this in favour of #6
