### ISSUE TITLE
frame for decoration

### ISSUE THREAD

**Issue by araimbekoff** [pulilab/vue-qr-reader#5]
. I want this option out of the box, and there are several options.
Pleaaaaaase! =)

**Comment by araimbekoff** [comment]
![image](https://user-images.githubusercontent.com/14542690/37979519-99b68b62-320a-11e8-90fa-f24a330147e8.png)

**Comment by lordfuoco** [comment]
This is out of the scope of the plugin, it's easy doable 'from outside' the plugin with few css and a transparent image.

We want to keep this plugin as simple as possible and to only solve the QR scanning problem
