### ISSUE TITLE
Project lacks license

### ISSUE THREAD

**Issue by ripern** [pulilab/vue-qr-reader#7]
This library does not seem to have a license or am I missing something? If you don't mind picking one, MIT would be nice.

**Comment by lordfuoco** [comment]
@ripern Hi! the package json state MIT license.
This should be enough but if you think it should be stated somewhere else please let us know (as usual any PR even just for docs is welcomed )

**Comment by ripern** [comment]
Hi! Thanks for the quick response!
It would be nice with a LICENSE file stating it. 
I first did a fork a was gonna fix it and PR you but then realized I didn't know what
to put as an author for license, so better if you could do it, https://help.github.com/articles/adding-a-license-to-a-repository/

Thanks in advance!

**Comment by lordfuoco** [comment]
@ripern Thank you for the tip, license added!
